(("scimax" . ((user-emacs-directory . "~/scimax")))
 ("crafted" . ((user-emacs-directory . "~/crafted-emacs")
	       (env . (("CRAFTED_EMACS_HOME" . "~/.config/crafted-emacs"))))
  )
 ("default" . ((user-emacs-directory . "~/emacs-from-scratch"))))
